mqtt_in:
  host: "localhost"
  port: 1883
  username: "user"
  password: "pass"

mqtt_out:
  host: "localhost"
  port: 1883
  username: "user"
  password: "pass"

rewrite_rules:
  - from: "topic/devices/+/up"
    to: "strom/+/wh"
    parser: "wh_parser"
  - from: "topic/devices/+/up"
    to: "strom/+/battery"
    parser: "battery_parser"
