mqtt:
  broker: "<HOSTNAME>"
  port: 1883
  username: "username"
  password: "password"
topics:
  - sub_topic: "original/topicwithwildcard/#"
    pub_topic: "targettopic/2ndlevel"
    parser:
      type: "json"
      key: "temperature"
  - sub_topic: "original/topicwithwildcard/#"
    pub_topic: "targettopic/2ndlevel"
    parser:
      type: "regex"
      pattern: "status=(\\w+)"
  - sub_topic: "original2"
    pub_topic: "targettopic2/"    
